### ISSUE TITLE
Create an initial power point from sample XML

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/threat-intelligence-reporting#2]
- Create an initial PowerPoint from sample XML.
- Use some sample XMLs from forensic-workbench
- Select a number of XMLs and create a python script to extract and process/integrate the results into a pptp presentation

Example: https://github.com/filetrust/GW-Test-Files/tree/master/xml-reports 

Details about the 7 initial slides: https://github.com/filetrust/threat-intelligence-reporting

**Comment by GINAGC** [comment]
Please add here what you have so far.

**Comment by MaNe2020** [comment]
I created the PR, 6 days ago for all that I have till now. 
Let me ping for approval tomorrow.

**Comment by MaNe2020** [comment]
@GINAGC I think we can close this one?

**Comment by GINAGC** [comment]
Initial script and presentation delivered by Marija.
